@startuml
'https://plantuml.com/sequence-diagram

entity User{
    + PK user_id : INT
    + private_info : PrivateInfo
    + username : varchar(64)
    + password : varchar(64)
    + role : Role
    + manager : User
    + created_at : timestamp
}


entity PrivateInfo{
    + PK private_info_id: INT
    + firstname : varchar(64)
    + lastname : varchar(64)
    + dateOfRegistration : date
    + dateOfBirth : date
    + address : Address
    + phone : varchar(15)
    + email : varchar(64)
    + comment: varchar(255)
    + created_at : timestamp
}

entity Address{
    + PK address_id : INT
    + country : varchar(64)
    + city : varchar(64)
    + postcode : varchar(6)
    + street : varchar(64)
    + houseNumber : INT
    + info : varchar(64)
}

entity Role{
    + PK role_id : INT
    + description : varchar(128)
}


entity Account {
    + PK account_id : INT
    + customer : Customer
    + account_type: AccountType
    + balance : DECIMAL(10,2)
    + created_at : DATETIME
    + requisites : Requisites
    + currency : varchar(3)
    + fees : Fees
}
entity AccountType{
    + account_type_id: INT
    + account_type_name : varchar(64)
    + description: varchar(255)
}
entity Fees{
        +PK fees_id : INT
        + maintenance_fee : DECIMAL(15, 2)
        + send_fee : DECIMAL(15, 2)
        + receive_fee: DECIMAL(15, 2)
        + funded_rate : DECIMAL(15, 2)
        + start_date : DATETIME
        + end_date : DATETIME
}
entity Transaction {
    + PK transaction_id : INT
    + account_from : Account
    + account_to : Account
    + amount : DECIMAL(10,2)
    + currency : varchar(3)
    + description : varchar(255)
    + transaction_date : DATETIME
    + transaction_type : TransactionType
    + transaction_status : TransactionStatus
    + created_at : timestamp
}

entity TransactionStatus{
    + PK transaction_status : INT
    + transaction_description : varchar(64)
}
entity TransactionType{
    + PK transaction_type_id : INT
    + transaction_type_name : varchar(64)
    + transaction_fee: DECIMAL(15, 2)
    + description: varchar(255)
}

entity Card {
    + PK card_id : INT
    + account : Account
    + card_number : varchar(16)
    + card_type : varchar(32)
    + Expiration_date : date
    + security_code : varchar(3)
    + created_at : timestamp
}
entity Bank{
    + PK bank_id : INT
    + bank_name : varchar(64)
    + swift : varchar(16)
    + address : Address
}

entity BankAccount{
    + PK account_id : Account
    + iban : varchar(16)
    + bank : Bank
}
entity Requisites{
    + PK id : INT
    + reciever_tax_number: INT
    + receiver_name: varchar(128)
    +  receiver_registration_address : Address
    +  Beneﬁciary bank: Bank
    +  receiver_account_number: Account
}




PrivateInfo -- Address : address_id
User --|{ Account : customer_id
User -- PrivateInfo : private_info_id
User -- Role : role_id
User --o{User
Account --o{ Transaction : account_sender_id
Account --o{ Transaction : account_receiver_id
Transaction -- TransactionStatus : transaction_status_id
Account --o{ Card
Transaction }o-- TransactionType : transaction_type_id
Account }o--|| AccountType : account_type_id
Bank --o{ BankAccount : bank_id
BankAccount -- Account : account_id
Account --Fees : fees_id
@enduml
